-   id: js-beautify
    name: js-beautify
    entry: js-beautify
    files: \.xml$
    args: []

    # Use additional_dependencies to install the actual node package
    additional_dependencies: []
    minimum_pre_commit_version: 0.7.0
